apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus-server
  name: prometheus-server
spec:
  ports:
    - name: "prometheus-port"
      port: 9090
      targetPort: prometheus-port
  selector:
    service: prometheus-server
  type: NodePort
