build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy_app:
  stage: deploy
  script:
    - cd ./helm/chart_app
    - helm upgrade --install --create-namespace --namespace myapp --values values.yml app-db .

deploy_log:
  stage: deploy
  script:
    - cd ./helm/chart_promtail
    - helm upgrade --install --create-namespace --namespace logging promtail . 

deploy_mon:
  stage: deploy
  script:
    - cd ./prometheus 
    - docker-compose up -d
    - cd ../
    - cd ./helm/chart_prometheus
    - helm upgrade --install --create-namespace --namespace monitoring prometheus .
 