global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram_bot'

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: 'YOUR_TOKEN'
    api_url: 'https://api.telegram.org'
    chat_id: 'CHAT_ID'
    parse_mode: 'HTML'