apiVersion: v1
kind: Service
metadata:
  labels:
    service: app
  name: app
spec:
  ports:
    - name: "app-port"
      port: 3003
      targetPort: app-port
  selector:
    service: app
  type: LoadBalancer

