apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              default: "true"
  podSelector:
    matchLabels:
      default: "true"
